---
# This playbook contains common tasks in this role

- name: check if pass4SymmKey is not hashed
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
  shell: "{{ splunk_home }}/bin/splunk btool server list clustermaster:{{ hostvars[cm_outer]['idxc_name'] }} | egrep -e '^pass4SymmKey = \\$1\\$'"
  register: grep_result
  check_mode: False
  failed_when: "grep_result.rc > 1"
  changed_when: "grep_result.rc != 0"
  notify: restart splunk
