---
# Sets configs for splunk in etc/system/local files

- name: "setting configs in file {{ splunk_conf_list_items.key }}.conf"
  tags:
    - splunk
    - splunk_conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/{{ splunk_conf_list_items.key }}.conf"
    section: "{{ item.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  with_items: "{{ splunk_conf_settings_list }}"
  when: splunk_conf_settings_list|length > 0
