---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - splunk_common
  debug: msg="role '{{ role_name }}' start"

- include_tasks: check_systemctl.yml

- include_tasks: set_splunk_version.yml
