---
# This playbook installs a splunk licenses

- name: loop through the license files
  tags:
    - splunk
    - license_master
  include_tasks:
    file: add_license.yml
  with_items: "{{ splunk_license_file }}"
  loop_control:
    loop_var: splunk_license_file_name
  when: splunk_license_file is defined
