---
# Main playbook for this role

- name: apply baseconfig app org_cluster_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_cluster_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_search_base'
    app_path: '{{splunk_home}}/etc/shcluster/apps'
    splunk_search_peer_list: "{{ hostvars[groups['search_peer_'+splunk_env_name+'_'+search_peer_name][0]]['splunk_search_peer_list'] }}"
  with_items: "{{ splunk_search_peer_name_list }}"
  loop_control:
    loop_var: search_peer_name
  when: splunk_search_peer_idxc_list|default([])|length > 0
