---
# This playbook contains common tasks in this role

- name: check pass4SymmKey not hashed
  tags:
    - splunk
    - deployer
  shell: "{{ splunk_home }}/bin/splunk btool server list shclustering | egrep -e '^pass4SymmKey = {{splunk_shc_pass}}$'"
  register: grep_result
  check_mode: False
  failed_when: "grep_result.rc > 1"
  changed_when: "grep_result.rc == 0"

- name: restart splunk for password hashing
  tags:
    - splunk
    - deployer
  service: name=splunk state=restarted
  become: yes
  become_user: root
  when: "grep_result.rc == 0"