---
# This playbook install a hosts file for all the hosts

#- name: append hosts to /etc/hosts
#  tags:
#   - configuration
#  blockinfile:
#    path: /etc/hosts
#    block: "{{ lookup('file', 'files/etc/hosts') }}"

- name: append hosts to /etc/hosts
  tags:
    - common
    - hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip_addr }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items: "{{ splunk_hosts }}"
