---
# This playbook installs additional os packages

- name: install additional os packages
  tags:
    - common
    - packages
  package:
    name: "{{ packages }}" 
    state: latest
  when: packages|default()
