---
# This playbook contains tasks in this role

- name: check if deployment server is configured
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_deploymentclient
  shell: "{{ splunk_home }}/bin/splunk show deploy-poll -auth admin:{{ splunk_admin_password }}"
  become: yes
  become_user: "{{ splunk_user }}"
  register: need_splunk_restart
  check_mode: False
  changed_when: need_splunk_restart.stdout.find('is not set') != -1

- name: restart splunk for deployment server configuration
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_deploymentclient
  shell: "{{ splunk_home }}/bin/splunk restart"
  become: yes
  become_user: "{{ splunk_user }}"
  when: need_splunk_restart.stdout.find('is not set') != -1 and splunk_deployment_server|default()|length > 0
