---
# This playbook install the base config app

- name: "({{ app_name }}) setting tcpout:primary_indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout:primary_indexers
    option: server
    value: "{{splunk_idxc_server_list}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
