---
# This playbook install the base config app

- name: "({{ app_name }}) configure some indexes"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  blockinfile:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    insertafter: "# CUSTOMER INDEXES"
    marker: "# {mark} ANSIBLE MANAGED BLOCK Index: {{ item }}"
    content: |
      [{{ item }}]
      homePath   = volume:primary/{{ item }}/db
      coldPath   = volume:primary/{{ item }}/colddb
      thawedPath = $SPLUNK_DB/{{ item }}/thaweddb
  with_items: "{{ splunk_indexes | default('test') }}"
  notify: restart splunk
