---
# This playbook install the base config app

- name: "({{ app_name }}) setting license master_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_full_license_server
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: license
    option: master_uri
    value: "https://{{splunk_license_master|first}}:8089"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
