- name: restart splunk
  tags:
    - splunk
    - splunk_enterprise
  service:
    name: "{{splunk_service_name}}"
    state: restarted
  become: yes
  become_user: root
  when: app_path == splunk_home + '/etc/apps'
