---
# This playbook install the apps required in a server

- name: create splunk install dir
  tags:
    - splunk
    - splunk_enterprise
  file:
    path: "{{ splunk_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: checking if splunk is installed
  tags:
    - splunk
    - splunk_enterprise
  stat:
    path: "{{ splunk_home }}/bin"
  register: splunk_path

- name: splunk is installed here
  tags:
    - splunk
    - splunk_enterprise
  debug: msg='splunk is already installed under {{ splunk_home }}/bin'
  when: splunk_path.stat.exists

- name: create splunk directory
  tags:
    - splunk
    - splunk_enterprise
  file:
    path: "{{ splunk_home }}"
    state: directory
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: 0755

- name: find splunk archive file
  tags:
    - splunk
    - splunk_enterprise
  command: find {{splunk_software}} -type f -name {{splunk_install_app}}-{{splunk_version}}-\*-Linux-x86_64.tgz
  become: no
  register: splunk_archive
  delegate_to: localhost
  when: splunk_path.stat.exists == false

- name: install splunk binaries
  tags:
    - splunk
    - splunk_enterprise
  unarchive: src={{item}} dest="{{ splunk_install_dir }}/" owner={{ splunk_user }} group={{ splunk_group }} creates=yes
  with_items: "{{ splunk_archive.stdout_lines }}"
  become: yes
  become_user: "{{ splunk_user }}"
  when: splunk_path.stat.exists == false and splunk_archive.rc == 0

- name: accept license and start splunk
  tags:
    - splunk
    - splunk_enterprise
  command: "{{ splunk_home }}/bin/splunk start --accept-license"
  become: yes
  become_user: "{{ splunk_user }}"
  when: splunk_path.stat.exists == false

- name: change splunk admin password
  tags:
    - splunk
    - splunk_enterprise
  command: "{{ splunk_home }}/bin/splunk edit user admin -password '{{splunk_admin_password}}' -auth admin:changeme"
  become: yes
  become_user: "{{ splunk_user }}"
  when: splunk_path.stat.exists == false

- name: enable boot-start
  tags:
    - splunk
    - splunk_enterprise
  command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ splunk_user }}"
  when: splunk_path.stat.exists == false and use_systemctl != true

- name: Install splunk service
  tags:
    - splunk
    - splunk_enterprise
  template:
    src: "etc/systemd/system/{{ splunk_service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ splunk_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  when: use_systemctl == true

- name: commit changes to systemctl
  tags:
    - splunk
    - splunk_enterprise
  command: systemctl daemon-reload
  when: use_systemctl == true

- name: enable and start splunk service
  tags:
    - splunk
    - splunk_enterprise
  service:
    name: "{{ splunk_service_name }}"
    state: started
    enabled: yes
