---
# Main playbook for this role

- name: "check for splunk fresh install"
  tags:
    - splunk
    - splunk_enterprise
  stat: path={{ splunk_home }}
  register: splunk_stat

- include: users.yml
- include: install.yml
- include: ulimit_thp.yml
- include: ui_config.yml

- name: final splunk restart after base install
  tags:
    - splunk
    - splunk_enterprise
  command: "{{ splunk_home }}/bin/splunk restart"
  become: yes
  become_user: "{{ splunk_user }}"
  when: not splunk_stat.stat.exists
