---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - search_head
  debug: msg="role '{{ role_name }}' start"

- name: "check for systemctl"
  tags:
    - splunk
    - splunk_enterprise
  stat:
    path: /bin/systemctl
  register: systemctl

- set_fact:
    use_systemctl: false
    splunk_service_name: splunk
  when: systemctl.stat.exists == false

- name: "check for splunk fresh install"
  tags:
    - splunk
    - splunk_enterprise
  stat: path={{ splunk_home }}
  register: splunk_stat

- name: "create splunk user and group"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: users.yml

- name: "install the splunk software"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: install.yml

- name: "set ulimits and disable THP"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: ulimit_thp.yml
  when: splunk_install_app == 'splunk'

- name: "user interface configuration"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: ui_config.yml

- name: final splunk restart after base install
  tags:
    - splunk
    - splunk_enterprise
  service:
    name: "{{ splunk_service_name }}"
    state: restarted
  become: yes
  become_user: root
  when: not splunk_stat.stat.exists
