---
# Main playbook for this role

- name: "check for splunk fresh install"
  tags:
    - splunk
    - splunk_enterprise
  stat: path={{ splunk_home }}
  register: splunk_stat

- name: "create splunk user and group"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: users.yml

- name: "install the splunk software"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: install.yml

- name: "set ulimits and disable THP"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: ulimit_thp.yml
  when: splunk_install_app == 'splunk'

- name: "user interface configuration"
  tags:
    - splunk
    - splunk_enterprise
  include_tasks: ui_config.yml

- name: final splunk restart after base install
  tags:
    - splunk
    - splunk_enterprise
  command: "{{ splunk_home }}/bin/splunk restart"
  become: yes
  become_user: "{{ splunk_user }}"
  when: not splunk_stat.stat.exists
