---
# This playbook install the base config app

- name: check if shcluster config is initialized
  tags:
    - splunk
    - search_head
    - shcluster
  shell: "{{ splunk_home }}/bin/splunk btool server list shclustering | egrep -e '^disabled = true$'"
  register: need_shcluster_init
  check_mode: False
  failed_when: "need_shcluster_init.rc > 1"
  changed_when: "need_shcluster_init.rc == 0"

- name: init shcluster member
  tags:
    - splunk
    - search_head
    - shcluster
  shell: "{{ splunk_home }}/bin/splunk init shcluster-config -shcluster_label {{ splunk_shc_label }} -mgmt_uri https://{{ ansible_hostname }}:8089 -replication_port {{splunk_shc_replication_port}} -secret {{splunk_shc_pass}} -auth admin:{{splunk_admin_password}}"
  become: yes
  become_user: splunk
  when: need_shcluster_init.rc == 0

- name: restart splunk for cluster init
  tags:
    - splunk
    - search_head
    - shcluster
  service: name=splunk state=restarted
  become: yes
  become_user: root
  when: need_shcluster_init.rc == 0

- name: setting conf_deploy_fetch_url
  tags:
    - splunk
    - search_head
    - shcluster
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: shclustering
    option: conf_deploy_fetch_url
    value: "https://{{splunk_shc_deployer}}:8089"
    owner: splunk
    group: splunk
    mode: 0600

- name: restart splunk before bootstrapping
  tags:
    - splunk
    - search_head
    - shcluster
  service: name=splunk state=restarted
  become: yes
  become_user: root
  when: need_shcluster_init.rc == 0

- name: check if shcluster is bootstrapped
  tags:
    - splunk
    - search_head
    - shcluster
    - bootstrap
  shell: "{{ splunk_home }}/bin/splunk show shcluster-status -auth admin:{{ splunk_admin_password }}"
  become: yes
  become_user: splunk
  register: need_shcluster_bootstrap
  check_mode: False
  failed_when: need_shcluster_bootstrap.rc != 0 and need_shcluster_bootstrap.rc != 22
  changed_when: need_shcluster_bootstrap.rc == 22
  when: ansible_hostname == splunk_shc_captain

- name: bootstrap search head cluster
  tags:
    - splunk
    - search_head
    - shcluster
    - bootstrap
  shell: "{{ splunk_home }}/bin/splunk bootstrap shcluster-captain -servers_list {{splunk_shc_server_list}} -auth admin:{{ splunk_admin_password }}"
  become: yes
  become_user: splunk
  notify: push shcluster bundle
  when: ansible_hostname == splunk_shc_captain and need_shcluster_bootstrap.rc == 22

- name: check if shcluster is service ready
  tags:
    - splunk
    - search_head
    - shcluster
    - bootstrap
  shell: "{{ splunk_home }}/bin/splunk show shcluster-status -auth admin:{{ splunk_admin_password }}"
  become: yes
  become_user: splunk
  register: result
  until: "result.stdout.find('service_ready_flag : 1') != -1"
  retries: 15
  delay: 10
  when: ansible_hostname == splunk_shc_captain and need_shcluster_bootstrap.rc == 22

- name: update dserver on monitoring_console
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
