---
# This playbook contains common tasks in this role

- name: apply baseconfig app org_search_volume_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_search_volume_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_search_volume_indexes'
    app_path: '{{splunk_home}}/etc/apps'

- name: apply baseconfig app org_all_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexes'
    app_path: '{{splunk_home}}/etc/apps'

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/apps'

- name: apply baseconfig app org_cluster_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_cluster_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: groups.role_deployment_server is not defined or inventory_hostname in groups.role_deployment_server


- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: groups.role_deployment_server is defined and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/apps'
  when: groups.role_deployment_server is not defined

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  when: groups.role_deployment_server is not defined and groups.role_license_master is defined and inventory_hostname not in groups.role_license_master

- include: check_pass.yml
  with_items: 
    - "{{ splunk_idxc_cm_list }}"
  loop_control:
    loop_var: cm_outer

- name: update serverclass on deployment_server
  include_role:
    name: deployment_server
    tasks_from: update_serverclass

- name: update dserver on monitoring_console
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
