---
# This playbook contains common tasks in this role

- name: start search single head
  tags:
    - splunk
    - search_head
    - shsingle
  debug: msg="Configuring single search head"

- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0 and splunk_license_master|default()|length > 0 and inventory_hostname not in groups.role_license_master

- name: apply baseconfig app org_search_volume_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_search_volume_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_search_volume_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_all_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_cluster_search_base on deployment_server
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_cluster_search_base
  include_role:
    name: baseconfig_app
  delegate_to: '{{splunk_deployment_server}}'
  vars:
    app_name: 'org_cluster_search_base'
    app_path: '{{ splunk_home }}/etc/deployment-apps'
    splunk_search_peer_list: "{{ hostvars[groups['search_peer_'+splunk_env_name+'_'+search_peer_name][0]]['splunk_search_peer_list'] }}"
  with_items: "{{ splunk_search_peer_name_list }}"
  loop_control:
    loop_var: search_peer_name
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_cluster_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_cluster_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0 and splunk_search_peer_idxc_list|length > 0

- include: check_pass.yml
  with_items: 
    - "{{ splunk_idxc_cm_list }}"
  loop_control:
    loop_var: cm_outer

- include: search_peers.yml

- name: update serverclass on deployment_server
  tags:
    - splunk
    - splunk_baseconfig
    - deployment_server
    - serverclass
  include_role:
    name: deployment_server
    tasks_from: update_serverclass

- name: update dserver on monitoring_console
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - search_peers
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
