---

- name: Add the slaves into spark /conf/slaves
  tags:
    - spark
    - spark_master
    - spark_master_conf_slaves
  lineinfile:
    dest: "{{spark_home}}/conf/slaves"
    regexp: ".*{{ hostvars[item]['ip_addr'] }}$"
    line: "{{ hostvars[item]['ip_addr'] }}"
    state: present
    owner: "{{spark_user}}"
    group: "{{spark_group}}"
    create: yes
  with_items:
    - "{{spark_sparkc_slave_list}}"
  when: spark_sparkc_slave_list|default()|length > 0

- name: install the sparkmaster systemd service
  tags:
    - spark
    - spark_master
  template:
    src: etc/systemd/system/sparkmaster.service.j2
    dest: /etc/systemd/system/sparkmaster.service
    owner: root
    group: root
    mode: 0644

- name: enable and start sparkmaster service
  tags:
    - spark
    - spark_master
  service:
    name: sparkmaster
    state: started
    enabled: yes
