---
# splunk_config.yml

os:
#  time_zone: "Europe/Zurich"
  packages:
    - java-1.8.0-openjdk

aws:
  #access_key_id: '' # defaults to ENV['AWS_ACCESS_KEY_ID']
  #secret_access_key: '' # ENV['AWS_SECRET_ACCESS_KEY']
  keypair_name: 'aws_key'
  #region: 'eu-central-1'
  #ami: 'ami-e3381508' # Ubuntu 16.04
  #ssh_username: 'ubuntu' # ami-e3381508
  ami: 'ami-c86c3f23' # Redhat 7.5
  ssh_username: 'ec2-user' # ami-c86c3f23
  #instance_type: 't2.micro'
  ssh_private_key_path: '~/.ssh/aws_key.pem'
  security_groups: ['Splunk']

spark_defaults:
#  spark_version: spark-2.3.0-bin-hadoop2.7
  # download from apache.org directly
  spark_download: true

#spark_dirs:
#    spark_software_dir: ../Software

spark_clusters:
  - sparkc_name: dfs

# Splunk hosts with its settings
splunk_hosts:
  # Spark Master
  - name: master
    roles:
      - spark_master
    sparkcluster: dfs

  # Spark Slave
  - name: slave1
    roles:
      - spark_slave
    sparkcluster: dfs

  # Spark Slave
  - name: slave2
    roles:
      - spark_slave
    sparkcluster: dfs
