- name: start role tasks
  tags:
    - spark
    - spark_software
  debug: msg="role '{{ role_name }}' start"

- name: "create spark user and group"
  tags:
    - spark
    - spark_software
  include_tasks: users.yml
  when: sparkc_name is defined

- name: checking if spark is installed
  tags:
    - spark
    - spark_software
  stat:
    path: "{{ spark_home }}/sbin/start-all.sh"
  register: spark_path
  when: sparkc_name is defined

- name: spark is installed here
  tags:
    - spark
    - spark_software
  debug: msg='spark found as {{ spark_home }}/sbin/start-all.sh'
  when: spark_path.stat.exists
  when: sparkc_name is defined

- name: "install the spark software"
  tags:
    - spark
    - spark_software
  include_tasks: install.yml
  when: sparkc_name is defined and spark_path.stat.exists == false
