---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
  debug: msg="role '{{ role_name }}' start"

- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: install certs for web ssl
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
    - org_all_search_base
    - web_ssl
  include_role:
    name: baseconfig_app
    tasks_from: org_all_search_base_certs
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0 and splunk_license_master|default()|length > 0 and inventory_hostname not in groups.role_license_master

- name: apply baseconfig app org_all_indexer_base
  tags:
    - splunk
    - splunk_baseconfig
    - heavy_forwarder
    - org_all_indexer_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexer_base'
    app_path: '{{splunk_home}}/etc/apps'
  notify: restart splunk
  when: splunk_deployment_server|default()|length == 0

- name: update serverclass on deployment_server
  tags:
    - splunk
    - splunk_baseconfig
    - deployment_server
    - serverclass
  include_role:
    name: deployment_server
    tasks_from: update_serverclass

- name: update dserver on monitoring_console
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - search_peers
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
