- name: "push shcluster bundle"
  tags:
    - splunk
    - search_head
    - shcluster
    - shsingle
  shell: "{{ splunk_home }}/bin/splunk apply shcluster-bundle -target https://{{splunk_shc_captain}}:8089 -auth admin:{{ splunk_admin_password }} --answer-yes"
  become: yes
  become_user: "{{ splunk_user }}"
  delegate_to: "{{ splunk_shc_deployer }}"
